spring.application.name=auth-service

server.port=8083

secret.key=ghhfHADHFLD-FHADLFALDHFADHF-AFADFYEFAEDERYFAFJEF

spring.grpc.server.port=9091


eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

